### ISSUE TITLE
Example of .elasticbeanstalk/config.yml

### ISSUE THREAD

**Issue by imgarylai** [awslabs/eb-java-scorekeep#10]
This is a really great work! You help me a lot! 

I have a question about deploy to elastic beanstalk. 

You ignore the file of `.elasticbeanstalk/config.yml`. 

Do we need to add 

```
deploy:
  artifact: build/libs/elit-compute-java-0.1.0.war
``` 

These line for deployment? 

Thanks

**Comment by mwunderl** [comment]
Hi Gary,

This project uses features of the Beanstalk Java platform to build the JAR on the EC2 instances, so you don't need to upload a build artifact. If you use the Tomcat platform, then yes, you would want to configure the EB CLI to deploy the WAR file as you show.

Thanks,
-Michael

**Comment by imgarylai** [comment]
@mwunderl  

Thanks for your reply. I solved my question but forgot to come back and close this issue. 

Also, I create an hello world example showing the eb config of a Spring boot app. It shows how I solve my issue as well. Here is the link: https://github.com/imgarylai/eb-java

**Comment by mwunderl** [comment]
Thanks Gary. I passed on your feedback about Gradle to the service team.
