### ISSUE TITLE
Gradle build is not working

### ISSUE THREAD

**Issue by smoell** [awslabs/eb-java-scorekeep#11]
Tried to build the application as described in the README, got the following error (used Cloud9 as environment):

docker run --rm -v /home/ec2-user/environment/eb-java-scorekeep:/home/gradle/project -w /home/gradle/project gradle:4.3 gradle build
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
make: *** [build] Error 1

**Comment by arbjerg** [comment]
Same problem here, it looks like this was build with an ancient gradle version (2.3)....

**Comment by hatahet** [comment]
As @arbjerg mentioned, this is due to building with an older gradle version. There are probably several ways to resolve this, but I updated `build.gradle` by removing the wrapper task:
```
@@ -43,6 +43,3 @@ dependencyManagement {                      
         mavenBom("com.amazonaws:aws-java-sdk-bom:1.11.67")   
     }                                                        
 }                                                            
-task wrapper(type: Wrapper) {                                
-    gradleVersion = '2.3'                                    
-}                                                            
```
and I modified `gradle-wrapper.properties` by changing the `distributionUrl` to a recent gradle version.

**Comment by Wenjng** [comment]
Worked for me following changes in build.gradle

springBoot {
    mainClass = "scorekeep.Application"
}
// task wrapper(type: Wrapper) {
//     gradleVersion = '2.3'
// }

**Comment by mwunderl** [comment]
Thanks everyone for your feedback. [Elastic Beanstalk's Java 8 platform](https://docs.amazonaws.cn/en_us/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.javase) still uses Gradle 2, so leaving the build as is for now. Added a new branch **corretto** to test on the new Corretto platforms that are in beta. When they are final, will migrate master.
