### ISSUE TITLE
overwrite the default nginx conf is not working with ebextensions

### ISSUE THREAD

**Issue by Aabhusan** [awslabs/eb-java-scorekeep#14]
I want to replaced the default nginx.conf file in elastic beanstalk with .ebextensions

I have created .ebextensions folder in my app's root directory. It looks like this:

/app
  - .ebextensions
      - nginx
          -  nginx.conf
      
i have followed the exact same process mentioned in the documentary https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-se-nginx.html
the deployment runs successfully but there  is still old nginx.conf file in my ec2instance managed by EB

anyone have any idea what is the issue?
Thanks in Advance

**Comment by Aabhusan** [comment]
@jpeddicord @labisso @hyandell @rahulrajaram hello everyone. anyone has any corrections to the process i have followed. do let me know asap.
thanks

**Comment by mwunderl** [comment]
Hi Aabhusan, if the feature is not working as documented you can try [repost.aws](https://repost.aws/tags/TAhZCjgK8eQvuM45ihyzqV6g) or contact customer support.

Thanks,
Michael
