### ISSUE TITLE
Depreciated code in example

### ISSUE THREAD

**Issue by jamie-wearsafe** [awslabs/eb-java-scorekeep#15]
Remove this use of "setTraceEntity"; it is deprecated.sonarlint(java:S1874)
The method setTraceEntity(Entity) from the type AWSXRayRecorder is deprecatedJava(67108967)
void com.amazonaws.xray.AWSXRayRecorder.setTraceEntity(Entity entity)
Deprecated Use Entity.run(Runnable) or methods in SegmentContextExecutors instead of directly setting the trace entity so it can be restored correctly.

Sets the trace entity value using the implementation provided by the SegmentContext resolved from the segmentContextResolverChain.

Parameters:

entity the trace entity to set

https://github.com/aws-samples/eb-java-scorekeep/blob/7af149a3218ac0c07571b9b4af00c4dedd65bb18/src/main/java/scorekeep/MoveFactory.java#L70

**Comment by srprash** [comment]
The deprecated API [`setTraceEntity`](https://docs.aws.amazon.com/xray-sdk-for-java/latest/javadoc/com/amazonaws/xray/AWSXRayRecorder.html#setTraceEntity(com.amazonaws.xray.entities.Entity)) is being used in the [`MoveFactory.java`](https://github.com/aws-samples/eb-java-scorekeep/blob/xray-worker/src/main/java/scorekeep/MoveFactory.java#L73) on the `xray-worker` branch.

**Comment by mwunderl** [comment]
Fixed in [6be0d587](https://github.com/aws-samples/eb-java-scorekeep/commit/6be0d5874b2d2aff8f4978c0d133f3181b50aa91)

**Comment by mwunderl** [comment]
released in [xray-v2](https://github.com/aws-samples/eb-java-scorekeep/releases/tag/xray-v2)
