### ISSUE TITLE
gradle build fails during deploy to EB

### ISSUE THREAD

**Issue by jeffie9** [awslabs/eb-java-scorekeep#17]
I am trying to follow the tutorial on https://docs.aws.amazon.com/xray/latest/devguide/xray-gettingstarted.html#xray-gettingstarted-deploy.  The deployment fails at building.  Line from eb-engine.log:

2022/01/06 19:58:21.554198 [ERROR] An error occurred during execution of command [app-deploy] - [Java Specific Build Application]. Stop running the command. Error: Build application failed on command gradle build with error: startProcess Failure: starting process "01build" failed: Command /bin/sh -c systemctl start 01build.service failed with error exit status 1. Stderr:Job for 01build.service failed because the control process exited with error code. See "systemctl status 01build.service" and "journalctl -xe" for details.

I tried to run `gradle build` locally and receive:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/aws-samples/eb-java-scorekeep/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'eb-java-scorekeep'.
> Failed to apply plugin 'spring-boot'.
   > Configuration with name 'runtime' not found.
```

**Comment by mwunderl** [comment]
Hi Jeff, thanks for trying the sample. I tried to reproduce with the 1.3 build but didn't get an error on the Java 8 platform. https://github.com/aws-samples/eb-java-scorekeep/pull/18 updates the platform to Corretto 8 and we'll update the tutorial with a new build.

I haven't seen that Gradle error. I'd try using the `gradlew` script as shown in `4-run-local.sh`

Thanks,
Michael

**Comment by mwunderl** [comment]
The v2 release for the `xray-gettingstarted` branch is published: https://github.com/aws-samples/eb-java-scorekeep/releases/tag/xray-gs-v2
